// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vmvdfmqkfuhavwodqttk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZtdmRmbXFrZnVoYXZ3b2RxdHRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyODgxODMsImV4cCI6MjA2OTg2NDE4M30.aZeWs1XYh2eyF-NgHHu0Vn1TxAXxjymlf_580A2TV04";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});